name: C
on: [push,pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        choiceL: [--disable-silent-rules, --enable-silent-rules, --enable-debug]
    steps:
      - uses: actions/checkout@v4
      - name: Create configure
        run: |
          sudo apt-get update -y
          sudo apt-get install autoconf automake libtool gcc gimp libgimp2.0-dev
          autoreconf -i
          automake
      - name: Choose configure
        run: ./configure ${{ matrix.choiceL }} --prefix=/usr
      - name: Make gimp-refocus-it plug-in
        run: make
      - name: Test make strip
        run: make strip
      - name: Test make install GIMP shared plug-in
        if: matrix.choiceL == '--disable-silent-rules'
        run: |
          sudo make install
          sudo make uninstall
